version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: ${TAG}
    image: pwoolvett/data-science-api:${TAG}
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        TAG: ${TAG}
    image: pwoolvett/data-science-api:dev-${TAG}
