version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pwoolvett/data-science-api:${VERSION}
  dev:
    build:
      context: .
      dockerfile: poetry.Dockerfile
      args:
        VERSION: ${VERSION}
    image: pwoolvett/data-science-api:poetry-${VERSION}
    depends_on:
      - api
